version: "3"

services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    env_file:
      - .env-prod
    volumes:
      - trading_app_db_prod:/var/lib/postgresql/data
    networks:
      - trading_app_network
  redis:
    image: redis:7.0-alpine
    container_name: "redis"
    networks:
      - trading_app_network
  app:
    container_name: "app"
    build:
      context: .
    env_file:
      - .env-prod
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    command: ["/fastapi_app/docker/app.sh"]
    networks:
      - trading_app_network
  celery:
    build:
      context: .
    container_name: "celery_app"
    env_file:
      - .env-prod
    command: ["/fastapi_app/docker/celery.sh", "celery"]
    depends_on:
      - redis
    networks:
      - trading_app_network
  flower:
    build:
      context: .
    container_name: "flower_app"
    env_file:
      - .env-prod
    command: [ "/fastapi_app/docker/celery.sh", "flower" ]
    depends_on:
      - redis
      - celery
    networks:
      - trading_app_network
    ports:
      - 5555:5555

volumes:
  trading_app_db_prod:
networks:
  trading_app_network:
