version: "3.0"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${DB_USER_TEST}
      - POSTGRES_PASSWORD=${DB_PASSWORD_TEST}
      - POSTGRES_DB=${DB_DB_TEST}
    ports:
      - ${DB_PORT_TEST}:5432
    networks:
      - custom
  redis:
    container_name: "redis"
    image: redis:7.0-alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - custom
networks:
  custom:
    driver: bridge
volumes:
  postgres_db: